# Manually create a dictionary mapping source names to their domains
source_domain_mapping = {
    'ETF Daily News': 'etfdailynews.com',
    'The Times of India': 'timesofindia.indiatimes.com',
    'GlobeNewswire': 'globenewswire.com',
    'Globalsecurity.org': 'globalsecurity.org',
    'Forbes': 'forbes.com',
    'BBC News': 'bbc.co.uk',
    'ABC News': 'abcnews.go.com',
    'Business Insider': 'businessinsider.com',
    'The Punch': 'punchng.com',
    'Al Jazeera English': 'aljazeera.com',
    'Marketscreener.com': 'marketscreener.com',
    'Phys.Org': 'phys.org',
    'International Business Times': 'ibtimes.com',
    'The Indian Express': 'indianexpress.com',
    'RT': 'rt.com',
    'NPR': 'npr.org',
    'Deadline': 'deadline.com',
    'Digital Trends': 'digitaltrends.com',
    'CNA': 'channelnewsasia.com',
    'Boing Boing': 'boingboing.net',
    'Time': 'time.com',
    'Android Central': 'androidcentral.com',
    'Gizmodo.com': 'gizmodo.com',
    'ReadWrite': 'readwrite.com',
    'Euronews': 'euronews.com',
    'Wired': 'wired.com',
    'CNN': 'cnn.com',
    'The Verge': 'theverge.com',
    'AllAfrica - Top Africa News': 'allafrica.com'
}